### ISSUE TITLE
If architecture after to is an array, it is not matched corretly

### ISSUE THREAD

**Issue by dariuszd21** [canonical/craft-grammar#31]
If there is a to set to an array e.g. (`to [amd64,arm64]`) and not single value (e.g. `to amd64`), grammar processor does not handle it correctly. The value is accepted, but it not validated against correctly.
I think it should either raise validation error if array is not an accepted value, or match architecture correctly.

Here is an example failing UT:
https://github.com/canonical/craft-grammar/commit/cc15ba9cc65b46b5451f541b640b46a7a1277a4a

**Comment by mr-cal** [comment]
I'm not sure how craft-grammar handles `to [amd64,arm64]` vs `to amd64,arm64` but the latter is never going to match. The `to` clause has to match every selector in its list - it's an `AND` operation, not an `OR`.

This is the not really documented and tested once [here](https://github.com/canonical/craft-grammar/blob/71be839c56ae18ce14664f1632ceb20b302e7f72/tests/unit/test_compound.py#L147).

**Comment by dilyn-corner** [comment]
Oh, that's interesting. I did not know it was a conjunction. That explains why the original docs never showcased `to [foo,bar]`. (This also means the example I provided to Graham in updating this docs is incorrect... 😅 ) The [documentation](https://snapcraft.io/docs/snapcraft-advanced-grammar) could be better phrased then; some synthesis of:

> The body of the to clause is taken into account if every (AND, not OR) selector is true for the target environment.

> Optionally an ‘on’ statement can precede a 'to' in the same line to form a compound statement. Used this way, the selectors of both statements have to be true. That is to say, both the build environment and the target have to be true for the body of the clause to be taken into account.


Is there any way it could be made into an `OR`?

**Comment by mr-cal** [comment]
> Is there any way it could be made into an OR? 

I don't know.  From what I have learned, this was designed with the idea that there would be more selectors than just the architecture. 

The snapcraft docs are misleading because they even show the syntax of `- on <selector>[,<selector>...]:`.

In the end, a yaml file should not use:
```yaml
    build-environment:
      - on amd64 to arm64,armhf:
        - FOO: BAR
      - on amd64 to riscv64:
        - FOO: BAZ
```

but instead must use:

```yaml
    build-environment:
      - on amd64 to arm64:
        - FOO: BAR
      - on amd64 to armhf:
        - FOO: BAR
      - on amd64 to riscv64:
        - FOO: BAZ
```
