### ISSUE TITLE
Unexpected behavior for multiple `to` statemens

### ISSUE THREAD

**Issue by mr-cal** [canonical/craft-grammar#89]
Given the following:

```yaml
parts:
  my-part:
    build-packages:
      - to armhf:
        - foo
      - to riscv64:
        - bar
      - else:
        - baz
```

Building for armhf will evaluate to `["foo", "baz"]` and building for riscv64 will evaluate to `["bar"]`.

This is an unexpected UX and there are no warnings or errors to explain the behavior.  Either craft-grammar should error when given multiple `to` statements with an `else` or it should properly handle this scenario.

Source: https://github.com/canonical/snapcraft/issues/5255
